nelmio_api_doc:
    documentation:
        info:
            title: Sport-API
            description: Rest API providing a CRUD for sports management
            version: 1.0.0

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc(.json)?$) # Accepts routes under /api except /api/doc
