plugins:
  phpcodesniffer:
    enabled: true

  markdownlint:
    enabled: true

  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false

exclude_patterns:
  - "bin/"
  - "config/"
  - "public/index.php"
  - "tests/"
  - "**/vendor/"
  - "migrations/"
  - "var/"
  - "src/Kernel.php"
